set(UTEST_MODULE_PATH "${CMAKE_CURRENT_LIST_DIR}/modules")

if(NOT UTEST_MODULE_PATH IN_LIST CMAKE_MODULE_PATH)
  list(APPEND CMAKE_MODULE_PATH "${UTEST_MODULE_PATH}")
endif()

include("${CMAKE_CURRENT_LIST_DIR}/utestTargets.cmake")
